Repository enter-at/python-aws-lambda-handlers, pull requests merged in 2019-07, with the labels that each got.

#23 add configuration for semantic-release
  .releaserc.yml
  .travis.yml
  package-lock.json
  package.json
Labels: size/M

#24 fix when the release process is triggered
  .travis.yml
  ci-scripts/release.sh
Labels: size/S

#25 update release script install process
  ci-scripts/release.sh
Labels: size/XS

#26 fix releaserc exec command to change version
  .releaserc.yml
Labels: size/XS

#27 remove unused hooks in pre-commit
  .pre-commit-config.yaml
Labels: size/XS

#29 fix how pypi release is done
  .travis.yml
  Makefile
  Pipfile
  Pipfile.lock
  ci-scripts/release.sh
Labels: size/M

#30 fix authentication for twine upload
  ci-scripts/release.sh
Labels: size/XS

#28 add setup instructions to README.md
  MANIFEST.in
  README.md
  setup.cfg
Labels: size/M

#31 fix misused `local` in bash script
  ci-scripts/release.sh
Labels: size/XS

#33 remove make tag target
  Makefile
Labels: size/XS

#34 fix pypi packaging
  README.md
  setup.cfg
Labels: size/XS

#35 add missing packaging setting
  setup.cfg
Labels: size/S

#36 enable travis codeclimate test reporter
  .codeclimate.yml
  .pre-commit-config.yaml
  .travis.yml
  Makefile
  Pipfile
  Pipfile.lock
  setup.cfg
Labels: size/S

#37 chore(editorconfig): exclude license file
  .editorconfig
  .gitignore
Labels: size/XS

#40 remove marshmallow usage in type hint
  lambda_handlers/__init__.py
  lambda_handlers/validators/marshmallow_validator.py
Labels: bug, size/XS

#39 add initial version of enhanced docs
  .gitignore
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.md
  docs/make.bat
  setup.cfg
Labels: documentation, size/XL

#41 Fix readthedocs build process
  README.md
  docs/conf.py
Labels: size/XS

#44 add api reference
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  ci-scripts/bump-python-version.sh
  docs/conf.py
  docs/requirements.txt
  docs/validators.md
  lambda_handlers/__init__.py
  lambda_handlers/errors.py
  lambda_handlers/types.py
  lambda_handlers/version.py
  setup.cfg
  setup.py
Labels: size/L

#52 add tox-pipenv-install to improve how tox runs tests
  Pipfile
  Pipfile.lock
  setup.cfg
Labels: size/L

#53 update Makefile to use newer install/package tools
  Makefile
  Pipfile
  Pipfile.lock
Labels: size/L

#55 Add event handler as a feature
  .travis.yml
  lambda_handlers/__init__.py
Labels: size/M

#56 fix build target in Makefile
  Makefile
  Pipfile
  Pipfile.lock
Labels: size/L
