Repository enter-at/python-aws-lambda-handlers, pull requests merged in 2019-06, with the labels that each got.

#7 add pre-commit settings
  .editorconfig
  .pre-commit-config.yaml
  Makefile
  Pipfile
  Pipfile.lock
Labels: size/L

#6 request and response validation
  .editorconfig
  .pre-commit-config.yaml
  .travis.yml
  Pipfile.lock
  lambda_handlers/__init__.py
  lambda_handlers/errors.py
  lambda_handlers/handlers/http_handler.py
  lambda_handlers/response/builder.py
  lambda_handlers/validators/jsonschema_validator.py
  lambda_handlers/validators/marshmallow_validator.py
  lambda_handlers/validators/tests/__init__.py
  lambda_handlers/validators/tests/test_jsonschema_validator.py
  lambda_handlers/validators/tests/test_marshmallow_validator.py
  lambda_handlers/validators/validator.py
  lambda_handlers/version.py
  setup.cfg
Labels: size/L

#8 add test to Validator
  Pipfile
  Pipfile.lock
  lambda_handlers/validators/jsonschema_validator.py
  lambda_handlers/validators/marshmallow_validator.py
  lambda_handlers/validators/tests/test_jsonschema_validator.py
  lambda_handlers/validators/tests/test_marshmallow_validator.py
  lambda_handlers/validators/tests/test_validator.py
  lambda_handlers/validators/validator.py
  setup.cfg
Labels: size/XL

#9 test(validator): check for correct inheritance
  lambda_handlers/validators/tests/test_jsonschema_validator.py
  lambda_handlers/validators/tests/test_marshmallow_validator.py
Labels: size/XS

#10 add tests for json formatters
  Makefile
  lambda_handlers/errors.py
  lambda_handlers/formatters/__init__.py
  lambda_handlers/formatters/json_formatter.py
  lambda_handlers/formatters/tests/__init__.py
  lambda_handlers/formatters/tests/test_json_formatter.py
  lambda_handlers/version.py
Labels: size/XS

#18 add test coverage to CI/CD configuration
  .travis.yml
  Makefile
  setup.cfg
Labels: size/S

#19 refactor response builder test
  lambda_handlers/response/tests/test_response_builder.py
Labels: size/XS

#21 add cors headers tests
  lambda_handlers/response/cors_headers.py
  lambda_handlers/response/tests/test_cors_headers.py
  lambda_handlers/response/tests/test_module_aliases.py
Labels: size/M
