Repository enter-at/python-aws-lambda-handlers, pull requests merged in 2019-10, with the labels that each got.

#76 Add line to exclude tests folders
  MANIFEST.in
Labels: size/XS

#78 chore(marshmallow): update to version 3.x
  Pipfile
  Pipfile.lock
  lambda_handlers/validators/marshmallow_validator.py
  lambda_handlers/validators/tests/test_marshmallow_validator.py
  setup.cfg
Labels: size/L

#80 fix(lambda_handler): ensure decorator forwards handler self
  lambda_handlers/handlers/lambda_handler.py
  lambda_handlers/handlers/tests/test_lambda_handler.py
Labels: size/M

#81 fix(lambda_handler): gracefully handle None return values
  lambda_handlers/handlers/http_handler.py
  lambda_handlers/handlers/tests/test_http_handler.py
Labels: size/M
